# See https://github.com/periph/gohci
version: 1
workers:
- name: beaglebone-4373
  checks:
  - cmd:
    - go
    - install
    - -v
    - ./cmd/headers-list
    - ./cmd/i2c-list
    - ./cmd/periph-info
    - ./cmd/spi-list
  - cmd:
    - periph-info
  - cmd:
    - headers-list
  - cmd:
    - i2c-list
  - cmd:
    - spi-list
- name: chip-a87d
  checks:
  - cmd:
    - go
    - install
    - -v
    - ./cmd/gpio-list
    - ./cmd/headers-list
    - ./cmd/i2c-list
    - ./cmd/periph-info
    - ./cmd/periph-smoketest
    - ./cmd/spi-list
  - cmd:
    - periph-info
  - cmd:
    - gpio-list
  - cmd:
    - headers-list
  - cmd:
    - i2c-list
  - cmd:
    - spi-list
  - cmd:
    - periph-smoketest
    - chip
  - cmd:
    - periph-smoketest
    - i2c-testboard
    - -bus
    - 1
  - cmd:
    - periph-smoketest
    - onewire-testboard
    - -i2cbus
    - 1
  - cmd:
    - periph-smoketest
    - sysfs-benchmark
    - -p
    - 1013
    - -short
  - cmd:
    - periph-smoketest
    - sysfs-benchmark
    - -p
    - 132
    - -short
  - cmd:
    - periph-smoketest
    - allwinner-benchmark
    - -p
    - 132
    - -short
  - cmd:
    - periph-smoketest
    - spi-testboard
- name: mbp
  checks:
  - cmd:
    - go
    - test
    - -race
    - ./...
  - cmd:
    - go
    - install
    - -v
    - ./cmd/gpio-list
    - ./cmd/headers-list
    - ./cmd/i2c-list
    - ./cmd/periph-info
    - ./cmd/spi-list
  - cmd:
    - periph-info
  - cmd:
    - gpio-list
  - cmd:
    - headers-list
  - cmd:
    - i2c-list
  - cmd:
    - spi-list
- name: odroid-483d
  checks:
  - cmd:
    - go
    - test
    - -cover
    - -bench=.
    - -benchtime=1000ms
    - -benchmem
    - ./...
    - ./...
  - cmd:
    - go
    - install
    - -v
    - ./cmd/gpio-list
    - ./cmd/headers-list
    - ./cmd/i2c-list
    - ./cmd/periph-info
    - ./cmd/periph-smoketest
    - ./cmd/spi-list
  - cmd:
    - periph-info
  - cmd:
    - gpio-list
  - cmd:
    - headers-list
  - cmd:
    - i2c-list
  - cmd:
    - spi-list
  - cmd:
    - periph-smoketest
    - odroid-c1
  - cmd:
    - periph-smoketest
    - i2c-testboard
  - cmd:
    - periph-smoketest
    - onewire-testboard
  - cmd:
    - periph-smoketest
    - spi-testboard
  - cmd:
    - periph-smoketest
    - sysfs-benchmark
    - -p
    - 97
    - -short
- name: raspberrypi-2f34
  checks:
  - cmd:
    - go
    - install
    - -v
    - ./cmd/gpio-list
    - ./cmd/headers-list
    - ./cmd/i2c-list
    - ./cmd/periph-info
    - ./cmd/periph-smoketest
    - ./cmd/spi-list
  - cmd:
    - periph-info
  - cmd:
    - gpio-list
  - cmd:
    - headers-list
  - cmd:
    - i2c-list
  - cmd:
    - spi-list
  - cmd:
    - periph-smoketest
    - i2c-testboard
  - cmd:
    - periph-smoketest
    - onewire-testboard
    - -i2cbus
    - 1
  - cmd:
    - periph-smoketest
    - spi-testboard
  - cmd:
    - periph-smoketest
    - sysfs-benchmark
    - -p
    - 12
    - -short
  - cmd:
    - periph-smoketest
    - bcm283x-benchmark
    - -p
    - 12
    - -short
- name: win10
  checks:
  - cmd:
    - go
    - test
    - -cover
    - -bench=.
    - -benchtime=1000ms
    - -benchmem
    - ./...
  - cmd:
    - go
    - test
    - -race
    - ./...
  - cmd:
    - go
    - vet
    - -all
    - -unsafeptr=false
    - ./...
