# Copyright 2020 The Periph Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# https://docs.codecov.io/docs/codecovyml-reference
# and
# https://docs.codecov.io/docs/coverage-configuration
coverage:
  precision: 1
  range: "40...80"
  round: nearest
  status:
    patch:
      default:
        target: 60%
        threshold: 10%
    project:
      default:
        target: 60%
        threshold: 10%
