// Copyright 2018 The Periph Authors. All rights reserved.
// Use of this source code is governed under the Apache License, Version 2.0
// that can be found in the LICENSE file.

// +build ignore

// static_gen generates static_prod.go from files in static/.

package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

const tmpl = `// Code generated by "go run internal/static_gen.go -o static_prod.go"; DO NOT EDIT.

// +build !debug

package main

const cacheControlContent = "Cache-Control:public,max-age=300"

func getContent(path string) []byte {
	return staticContent[path]
}

var staticContent = map[string][]byte{
{{range .}}	{{index . 0}}: {{index . 1}},
{{end}}}
`

func pipe(cmd []string, in io.Reader) ([]byte, error) {
	c := exec.Command(cmd[0], cmd[1:]...)
	c.Stdin = in
	c.Stderr = os.Stderr
	r, err := c.Output()
	if err != nil {
		err = fmt.Errorf("%s: %v", strings.Join(cmd, " "), err)
	}
	return r, err
}

func fillData(base string, content, raw []string) ([][2]string, error) {
	var data [][2]string
	for _, n := range content {
		p := filepath.Join(base, n)
		r, err := ioutil.ReadFile(p)
		if err != nil {
			return nil, err
		}
		ext := filepath.Ext(n)
		if r, err = pipe([]string{"minify", "--type", ext[1:]}, bytes.NewReader(r)); err != nil {
			if strings.HasSuffix(err.Error(), exec.ErrNotFound.Error()) {
				return nil, errors.New("Please install minify with: go get github.com/tdewolff/minify/cmd/minify")
			}
			return nil, err
		}
		data = append(data, [2]string{strconv.Quote(strings.Replace(p, "\\", "/", -1)), fmt.Sprintf("[]byte(%q)", r)})
	}
	for _, n := range raw {
		p := filepath.Join(base, n)
		r, err := ioutil.ReadFile(p)
		if err != nil {
			return nil, err
		}
		data = append(data, [2]string{strconv.Quote(strings.Replace(p, "\\", "/", -1)), fmt.Sprintf("[]byte(%q)", r)})
	}
	return data, nil
}

func mainImpl() error {
	output := flag.String("o", "", "output file, else stdout")
	flag.Parse()
	if flag.NArg() != 0 {
		return errors.New("unknown argument")
	}

	data, err := fillData(
		"static",
		[]string{"index.html"},
		[]string{"favicon.ico"})
	if err != nil {
		return err
	}

	t, err := template.New("").Parse(tmpl)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}
	r, err := pipe([]string{"gofmt", "-s"}, &buf)
	if err != nil {
		return err
	}
	if *output != "" {
		return ioutil.WriteFile(*output, r, 0666)
	}
	_, err = os.Stdout.Write(r)
	return err
}

func main() {
	if err := mainImpl(); err != nil {
		fmt.Fprintf(os.Stderr, "gen: %v\n", err)
		os.Exit(1)
	}
}
