// Copyright 2016 The PIO Authors. All rights reserved.
// Use of this source code is governed under the Apache License, Version 2.0
// that can be found in the LICENSE file.

// Package bcm283x exposes all BCM283x GPIO functionality, including pull
// resistors and edge triggered interupts.
//
// Internals
//
// It leverages Raspbian's /dev/giomem for all access except for edge based
// triggering, which uses gpio sysfs as it requires kernel cooperation to
// handle the interrupts generated by the CPU.
//
// This library cannot work without /dev/gpiomem. It could be rewritten to use
// /dev/mem but that requires running as root and defeats all security.
//
// Datasheet
//
// https://www.raspberrypi.org/wp-content/uploads/2012/02/BCM2835-ARM-Peripherals.pdf
package bcm283x
